apiVersion: apps/v1
kind: Deployment        
metadata:
  name: java-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java                                     
  template:                	                              
    metadata:
      labels:
        app: java                                  
    spec:
      containers:
        - image: java_app:latest
          imagePullPolicy: Never
          name: listener
          ports:
            - containerPort: 5000